openapi: 3.1.0
info:
  title: pogolo API
  description: API specification for pogolo
  version: 1.0.0
  license:
    name: GNU General Public License version 3
    url: https://opensource.org/license/gpl-3-0

servers:
  - url: http://{server}:{port}
    variables:
      server:
        default: "127.0.0.1"
      port:
        default: "5662"

components:
  schemas:
    InfoResponse:
      type: object
      required:
        - uptime
        - blocksFound
        - blockHeight
        - totalGophers
        - totalHashrate
        - bestDifficulty
        - tag
        - gophers
      properties:
        uptime:
          type: integer
          description: In seconds
        blocksFound:
          type: array
          description: Array of FoundBlockInfo
          items:
            $ref: "#/components/schemas/FoundBlockInfo"
        blockHeight:
          type: integer
          description: The height the pool is mining at
        totalGophers:
          type: integer
        totalHashrate:
          type: number
          description: In MH/s
        bestDifficulty:
          type: number
        tag:
          type: string
          description: The configured coinbase tag
        gophers:
          type: array
          description: List of active gophers
          items:
            $ref: "#/components/schemas/MiniGopherInfo"

    MiniGopherInfo:
      type: object
      required:
        - userAgent
        - extranonce1
      properties:
        userAgent:
          type: string
        extranonce1:
          type: string

    GopherInfo:
      type: object
      required:
        - address
        - averageShareTime
        - bestDifficulty
        - extranonce1
        - hashrate
        - nickname
        - protocolVersion
        - sharesAccepted
        - sharesRejected
        - targetDifficulty
        - uptime
        - userAgent
      properties:
        address:
          type: string
          description: On-chain address the miner is mining to
        averageShareTime:
          type: number
          description: float64 averaged share time, in seconds
        bestDifficulty:
          type: number
        extranonce1:
          type: string
        hashrate:
          type: number
          description: In MH/s
        nickname:
          type: string
        protocolVersion:
          type: number
          description: either 1 for SV1, or 2 for SV2
        sharesAccepted:
          type: integer
        sharesRejected:
          type: integer
        targetDifficulty:
          type: number
        uptime:
          type: integer
          description: In seconds
        userAgent:
          type: string

    FoundBlockInfo:
      type: object
      required:
        - difficulty
        - extranonce2
        - gopher
        - hash
        - height
        - nonce
        - timestamp
        - version
      properties:
        difficulty:
          type: number
        extranonce2:
          type: string
        gopher:
          type: string
          description: Gopher nickname or ID
        hash:
          type: string
          description: Byte-reversed block hash
        height:
          type: integer
        nonce:
          type: integer
          description: Header nonce
        timestamp:
          type: integer
          description: In seconds since unix epoch
        version:
          type: integer
          description: Header version
paths:
  /api/v1/info:
    get:
      summary: Get snapshot of current pool stats
      operationId: getInfo
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"

  /api/v1/gopher/{idOrNickname}:
    get:
      summary: Get snapshot of a gophers stats
      operationId: getGopherInfo
      parameters:
        - name: idOrNickname
          in: path
          required: true
          description: The gophers extranonce1 or nickname
          schema:
            type: string

      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GopherInfo"

  /openapi.yaml:
    get:
      summary: Get this Swagger spec
      operationId: getSwagger
      responses:
        "200":
          description: "Success"
          content:
            application/yaml:
              schema:
                type: string

  /metrics:
    get:
      summary: Get prometheus metrics
      operationId: getMetrics
      responses:
        "200":
          description: "Success"
          content:
            text/plain; version=0.0.4:
              schema:
                type: string
