[backend]
# RPC host:port, overridden by POGOLO_BACKEND_HOST
host = '[::1]:8332'
# RPC cookie path, relative is supported (takes precedence over rpcauth)
# cookie = ''
# RPC user:pass (ignored if cookie is set)
# overridden by POGOLO_BACKEND_RPCAUTH
# rpcauth = ''
# ZMQ endpoint to subscribe to 'hashblock' events
# overridden by POGOLO_BACKEND_ZMQHOST
# zmq_host = ''
# whether to use the btcd websocket interface
# websocket = false
# how quickly to poll for block updates, in milliseconds
# ignored if using websocket, and used for the connection retry interval with zmq
poll_interval = 500

[pogolo]
# will listen on all interface ips (takes precedence over ip)
interface = 'lo'
# ipv4, v6, or domain (domain will resolve all ips) (ignored if interface is set)
# overridden by POGOLO_HOST
# host = ''
# use 0 to pick a random port
port = 5661
# port for the api
http_port = 5662
# optional, required from sv1 clients if set
# password = ''
# will be replaced by default tag if too long (about 86 chars)
# customize it! add your swarm stats, like
# '/pogolo - gamma x1 - decentralize or die/'
tag = '/pogolo on Umbrel - webui test config - decentralize or die/'
# default on-chain address to mine to if not provided by client
# pool_address = ''
# minimum 0.16
default_difficulty = 1024.0
# how often to send new work to clients, in seconds
job_interval = 120
# how often we want shares on average, in seconds
target_share_interval = 5
# extranonce2 size in bytes, usually shouldnt be touched
# extranonce2_size = 8
# version bits as int32, ORed with the template version
# bip_version_bits = 0
# ignore the client-suggested difficulty
# ignore_suggested_difficulty = false
# disable automatic difficulty adjustment
# disable_vardiff = false
# file to log to (path resolution same as cookie)
# log_file = ''
